Q1. Is there any difference in the data type of variables list_ and array_list?
Yes, there is a difference:

list_ is a Python list.

array_list is a NumPy array.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))


Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


Q2. Print the data type of each and every element of both list_ and array_list:

In [3]:
# For list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# For array_list
print("\nData types in array_list:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [5]:
#Q3. If you change array_list to:
array_list = np.array(object=list_, dtype=int)

In [6]:
array_list = np.array(object=list_, dtype=int)

# Check data types again
print("Data types in list_:")
for element in list_:
    print(type(element))

print("\nData types in new array_list:")
for element in array_list:
    print(type(element))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in new array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [7]:
# Q4. Find the following characteristics of num_array:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
print("Shape of num_array:", num_array.shape)

# (ii) Size
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [8]:
# Q5. Create a 3×3 matrix containing only zeros using NumPy:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Q6. Create an identity matrix of shape (5,5):
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
